# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_lYCkBl2zULsKEXelV_V1tf2wPeRnY6s
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile utils.py
# import re
# 
# def process_tweet(tweet):
#     """
#     Function to clean a tweet: remove links, special characters, and convert to lowercase.
#     """
#     tweet = tweet.lower()  # Convert to lowercase
#     tweet = re.sub(r"http\S+|www\S+|https\S+", '', tweet, flags=re.MULTILINE)  # Remove links
#     tweet = re.sub(r'\W', ' ', tweet)  # Remove non-word characters
#     tweet = re.sub(r'\s+', ' ', tweet).strip()  # Remove extra spaces
#     return tweet
#

